[package]
name = "pista-sensors"
version = "0.0.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
binance = "0.18.4"
chrono = "0.4.22"
clap = {version = "3.0", features = ["derive"]}
env_logger = "0.9.0"
log = "0.4.17"
mpd = "0.0.12"
notify = "5.0.0"
reqwest = {version = "0.11.11", features = ["blocking"]}
serde = { version = "1.0.144", features = ["derive"] }
serde-xml-rs = "0.6.0"
serde_json = "1.0.82"
x11 = { version = "2.20.0", features = ["xlib"] }

[[bin]]
name = "pista-sensor-backlight-laptop"
path = "pista-sensor-backlight-laptop.rs"

[[bin]]
name = "pista-sensor-bluetooth"
path = "pista-sensor-bluetooth.rs"

[[bin]]
name = "pista-sensor-helium-account-balance"
path = "pista-sensor-helium-account-balance.rs"

[[bin]]
name = "pista-sensor-memory"
path = "pista-sensor-memory.rs"

[[bin]]
name = "pista-sensor-mpd"
path = "pista-sensor-mpd.rs"

[[bin]]
name = "pista-sensor-weather"
path = "pista-sensor-weather.rs"

[[bin]]
name = "pista-sensor-x11-keymap"
path = "pista-sensor-x11-keymap.rs"
